server:
    port: 8080

spring:
    # profiles:
    #     active: ${SPRING_PROFILE}
    webflux:
        base-path: ${CONTEXT_PATH}
    application:
        name : ecs-project
    config:
        import: optional:file:.env[.properties]
    r2dbc:
        url: r2dbc:postgresql://${R2DBC_HOST}:5432/${R2DBC_DB}
        username: ${R2DBC_USERNAME}
        password: ${R2DBC_PASSWORD}
        # pool:
        #     initialSize : 2
        #     maxSize :

cloud:
    aws:
        credentials:
        # profile-name: s3-file-user
        region:
            static: ap-northeast-1
            auto: false
        stack:
            auto: false
aws:
    access-key-id: access-id
    secret-key-id: secret-key
    s3-bucket: bucket-name
    s3-object-kms-keyId: object-id


